### ISSUE TITLE
Terralith swamp biomes do not have surface slime spawns

### ISSUE THREAD

**Issue by ApolloDatapacks** [Stardust-Labs-MC/Terralith#1]
The #minecraft:allows_surface_slime_spawns tag is not in the pack as of v2.3.5, meaning none of the Terralith swamp biomes can have surface slime spawns.
![image](https://user-images.githubusercontent.com/102649729/200764643-1b69d266-7095-4029-ba47-0fcda17c6ec2.png)

**Comment by catter1** [comment]
Fixed for future version 2.3.7
