### ISSUE TITLE
[Possible Bug] Terralith added birch trees suffering leaf decay on generation

### ISSUE THREAD

**Issue by Fish-screaming-in-agony** [Stardust-Labs-MC/Terralith#101]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.11

### Mod or datapack version?

Mod (Forge)

### Describe the bug

specifically this is 1.20.1
upon worldgen the birch trees added by terralith to birch forests suffer leaf decay and seemingly some leaves are not present upon generation, more trees could have this issue but so far I've not encountered such. I've put a screenshot here showing the odd leaves.
![leafdecay](https://github.com/Stardust-Labs-MC/Terralith/assets/161859064/a7cf8fbd-17e5-4c55-a23e-6ba1ff582ae0)

### Additional context

This is with nothing but terralith itself installed and on a different seed to the world I first noticed the issue on, albeit that world was modded so I procedually removed mods from my list until I got to just terralith.

I've refreshed my modlist, repaired the install and the issue persists.

**Comment by catter1** [comment]
What seed and coords is being used in the screenshot (or anywhere similar to it)?

**Comment by Fish-screaming-in-agony** [comment]
Screenshot Seed: -5691518937230421221
Screenshot Coords: X 162 / Y 93 / Z 327

seed of world I first found the issue:
5398916428069964103 - there's a birch forest right at the spawn area

**Comment by Fish-screaming-in-agony** [comment]
just to add to this I've explored the seed 5398916428069964103 further and found that the moonlight valley trees also suffer from this, alongside that the cherry trees present in the sakura grove (though for these trees the effect is rather minor and not to the extent of the birch forest), and the jungle trees as well also suffer from this.

coordinates are for seed 5398916428069964103 (second seed in the first message/non original screenshot seed)
Sakura grove coords: X 1570 / Y 106 / Z 1489
Moonlight Valley coords: X -1495 / Y 82 / Z 1181
Jungle coords: X 1532 / Y 92 / Z -302

there's probably more trees suffering from this but so far the birch trees are the most visible sufferers of it (and most common as far as I can see)
not every type of birch suffers from it though as the old growth birches seem just fine

**Comment by catter1** [comment]
Fixed in 2.5.0
