### ISSUE TITLE
[Bug] Crash with BiomesOPlenty - snowy_cherry_grove Conflict

### ISSUE THREAD

**Issue by serioos** [Stardust-Labs-MC/Terralith#102]
### What Minecraft version(s) does this apply to?

1.20

### Project version

Terralith_1.20.4_v2.4.11

### Mod or datapack version?

Datapack

### Describe the bug

The game crashes at new world generation (haven't tried loading an already made world with it). The snowy cherry grove from Terralith conflicts with every BiomesOPlenty biomes. I keep turning off the biomes that make the game crash in BiomesOPlenty's config, but it keeps conflicting with a new biome.

I first had the biomesOPlenty release version, then updated it to the latest beta BiomesOPlenty version, and it did not help.

I have these:

Minecraft Forge 1.20.1

Terralith_1.20.4_v2.4.11.jar
TerraBlender-forge-1.20.1-3.0.1.4.jar
BiomesOPlenty-1.20.1-18.0.0.598.jar
RegionsUnexploredForge-0.5.5+1.20.1.jar

Here's the crash log:

https://pastebin.com/Ch1BiyT7

Here's my modpack for testing:

[Kittycat-1.0.zip](https://github.com/Stardust-Labs-MC/Terralith/files/14894486/Kittycat-1.0.zip)

**Comment by catter1** [comment]
There is no error between Terralith and BoP. Rather, it is an issue with Cyclic. Insall [this mod](https://modrinth.com/mod/cyclic-crash-fixer) to fix it.

**Comment by serioos** [comment]
Wow, thank you so much for helping me. Yes, it was indeed Cyclic causing my crash and installing that mod helped me generate a world without crash. Thank you again.
