### ISSUE TITLE
[Bug] Terralith villages and Towns and Towers towns spawn next to each other

### ISSUE THREAD

**Issue by NilsMoller** [Stardust-Labs-MC/Terralith#104]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.11

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

When running Terralith and Towns and Towers on Fabric 1.20.1 the Terralith and Towns and Towers villages consistently spawn right next to each other. This is a compatibility issue. [Your wiki](https://stardustlabs.miraheze.org/wiki/Terralith#List_of_compatible_Fabric/Quilt_Mods) says the two mods are compatible.

![2024-04-11_13 47 01](https://github.com/Stardust-Labs-MC/Terralith/assets/41434155/01af66f6-adc2-4d35-9188-d47d90672815)

![2024-04-11_13 46 42](https://github.com/Stardust-Labs-MC/Terralith/assets/41434155/c85c265e-1b54-4f9d-8ba6-b230a43e7d6f)

**Comment by NilsMoller** [comment]
I incorrectly remembered where I saw the compatibility list and it's Towns and Towers saying it's compatible with Terralith. Not the other way around. I will post this issue on their github instead.

**Comment by catter1** [comment]
There is actually nothing that either of us can do about it. We are compatible in the sense that both of our structures will generate, and that T&T structures will generate in our biomes. However, as datapacks, we simply have zero tools to check for nor prevent each others' structures from generating near each other. This is the (only) small downside of using multiple datapacks/mods that add structures.

**Comment by NilsMoller** [comment]
That is very interesting, I did not know that it's such a limitation. Thank you!
