### ISSUE TITLE
[README] Superflat/Amplified/Large Biomes Issue

### ISSUE THREAD

**Issue by catter1** [Stardust-Labs-MC/Terralith#113]
### What Minecraft version(s) does this apply to?

All

### Project version

All

### Mod or datapack version?

All

### Describe the bug

Many people come to report a bug about superflat not working, or even the amplified or large biomes world types. There is nothing we can currently do about this. Please do not make a new issue about it, I will close it. Explanation:

Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds, since datapacks are applied on a per-world basis.

~~Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or Superflat.~~ This bug has since been fixed, but there are other barriers until we are physically able to support other world types. The main one being the ability to define custom biome parameter list presets.

Whenever we are physically able to support other world types, we will be doing so. But for now it is not possible.

**Comment by OsakaPhysics** [comment]
fix it pls

**Comment by BumbleBeetle** [comment]
Hey there. Terralith had caught my eye, but as someone with a preference for large biomes I was disappointed to find this issue. 
However, I noticed that [MC-260949](https://bugs.mojang.com/browse/MC-260949) had been marked as resolved at the end of November. I have just tested it myself and I can confirm the bug resolved for versions 1.21.2 onwards. With this being the case, would you consider supporting these alternative world types going forward?

**Comment by catter1** [comment]
Yes, you are correct that the bug has been marked as "cannot reproduce", as it was unknowingly fixed a few versions ago. I will need to update our FAQs to reflect that.

However, what I didn't make clear is that is not the only requirement to support other world types. For example, we also need the ability to define custom biome parameter list presets. Whenever we get the ability (and any other tweaks/changes/additions required) to make supporting other world types possible, we will 100% be doing so.

**Comment by BumbleBeetle** [comment]
Ah, that is unfortunate to see but quite understandable. Thank you for the prompt reply.

**Comment by SkySpnc** [comment]
Resolved with PR https://github.com/Stardust-Labs-MC/Terralith/pull/227, but for some reason refusing to test 🤔

**Comment by the-vindicar** [comment]
On [mod's Modrinth page](https://modrinth.com/datapack/terralith), there is a following claim:
> As of 2.6.0, the mod version of Terralith adds support for all world types. This means Terralith will respect superflat worlds, and work with the Single Biome, Large Biomes, and Amplified world types.

That said, at the moment of writing this comment mod version 2.6.0 seems to exist only for 1.21.11. Are there any plans to backport it to older game versions, or is it something ther relies on Mojang's code changes?

**Comment by catter1** [comment]
2.6.0 will be backported to 1.21.1, but that is it. The reason that other world types are now supported is because we depend on Lithostitched and implement our own code code, and it is not realistic for us to backport and maintain that for older versions.

**Comment by gagebug2008-art** [comment]
when exactly do you think it'll be ported

**Comment by catter1** [comment]
I do not have an answer right now. Recently I have been busy with updating everything to 26.1

**Comment by gagebug2008-art** [comment]
dang

**Comment by Yijare** [comment]
so no 1.20.1 backport. Sadge.

**Comment by catter1** [comment]
1.21.1 is finally getting its backport, so I will finally mark this as fixed.
