### ISSUE TITLE
[Enhancement] Config menu

### ISSUE THREAD

**Issue by MMG778** [Stardust-Labs-MC/Terralith#117]
### Describe your enhancement/improvement, with context and reasoning.

Please create a mod configuration menu or file for non-programming geniuses, so that we as players can configure all of Terralith's features, item, biomes, etc, because I would like to use Terralith with Terrestria, Nature's Spirit, Wilder Wild, Regions Unexplored and WWEE (William Wyther's) mod together, but there are certain biomes which I like more or don't like in others. For example Regions Unexplored, Wilder Wild, Terrestria, Nature's Spirit has an easily configurable config menu and config file. I hope this awesome thing can be done.

**Comment by catter1** [comment]
This is similar to #113. Because Terralith is actually a datapack disguised as a mod, this cannot easily be done. We could have to create an entire wrapper around the mod. While this is something that we would like to look into someday, currently we do not have the time nor resources for it.
