### ISSUE TITLE
[Bug] Superflat doesn't work

### ISSUE THREAD

**Issue by superloaf2** [Stardust-Labs-MC/Terralith#118]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.5.1

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

When i select superflat in the world creation menu, and generate the world, its not close to being "flat".
Would be nice if any of you fixed this issue

If the mod version is outdated, i'm sorry. 

### Additional context

PC Specifications (if you need them):
CPU: Intel 12400F 
GPU: Nvidia 4060 
RAM: 16G 3200MHz

**Comment by catter1** [comment]
Please see #113
