### ISSUE TITLE
[Bug] Small bug with description

### ISSUE THREAD

**Issue by frosthuuund** [Stardust-Labs-MC/Terralith#119]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.5.2~1.21 (pls add 1.21)

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

![2024-06-14_08 05 01](https://github.com/Stardust-Labs-MC/Terralith/assets/168279382/e7e3a5a6-5b01-4c85-bb90-b8caa58f8ca5)

**Comment by catter1** [comment]
This is not a bug - this is just how Minecraft handles high effect numbers.
