### ISSUE TITLE
[Bug]Worldgen failure for `terralith:cave/thermal/dripstone`

### ISSUE THREAD

**Issue by zly2006** [Stardust-Labs-MC/Terralith#123]
### What Minecraft version(s) does this apply to?

1.21

### Project version

Minecraft 1.21 , 2.5.2

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

See the log:
https://gist.github.com/zly2006/abf8221a330dfaea5c6ecdbf56d9fadf

**Comment by catter1** [comment]
Already fixed in 2.5.3, upgrade to that version

**Comment by zly2006** [comment]
Can confirm it has been fixed.
