### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by MMG778** [Stardust-Labs-MC/Terralith#124]
### What Minecraft version(s) does this apply to?

1.20

### Project version

newest

### Mod or datapack version?

Datapack

### Describe the bug

Dear Stardust Labs!

How can I remove certain biomes from world generation? Which files do I have modify or delete?

Thanks in advance!

**Comment by catter1** [comment]
Normally would copy/paste the text, but that's more difficult on mobile. So here's screenshots from our Discord server FAQ.
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/0d156872-6f30-423a-aaf0-b87a73bae38c)
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/9d8c19c1-dc26-482f-89ae-ceca7504c3c3)
