### ISSUE TITLE
[Bug] WorldGen Crash with minecraft:worldgen/placed_feature / terralith:cave/thermal/lichen_clay

### ISSUE THREAD

**Issue by brandoncamp16** [Stardust-Labs-MC/Terralith#125]
### What Minecraft version(s) does this apply to?

1.21

### Project version

2.5.3

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

When teleporting to -1615.500000, 90.000000, -7167.500000 on seed -5203240258495659746 the game crashes.

See the logs:

Server crash: https://gist.github.com/brandoncamp16/028198f1a9fa10909ab05c52284492a5

Client crash with only Fabric API and Terralith: https://gist.github.com/brandoncamp16/4451ed66b8de9be471cc74397ff1bc38

### Additional context

This first occurred on my server when pregenerating chunks with Chunky, but also happens on a client with only Fabric API and Terralith installed. The world freezes on the client and the server freezes when attempting to generate the chunks at that specific position.

**Comment by catter1** [comment]
Will take a look at it this weekend. I think I know what the issue is already, so should be a quick fix.

**Comment by catter1** [comment]
NTS: `terralith:cave/thermal/dripleaf_clay`

**Comment by ZewZack** [comment]
> NTS: `terralith:cave/thermal/dripleaf_clay`

hey sorry for bothering but I've same error. I don't really want to bother you but can I ask eta? thanks for your hard work.

**Comment by catter1** [comment]
I've had a busy week, so no time to work on it. Hopefully soon, but I can make no promises.

**Comment by catter1** [comment]
Fixed for upcoming 2.5.4
