### ISSUE TITLE
Scarlet mountains turn to dirt mountains with Tectonic increased world height

### ISSUE THREAD

**Issue by johalun** [Stardust-Labs-MC/Terralith#133]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.5.1

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Tectonic has a config option "increased_height" which increases the world height to 640. When setting this to true, what used to be scarlet mountains becomes just dirt/stone mountains. The terrain itself looks very similar regardless of this setting but the blocks are changed. The biome is still scarlet mountains.

**Comment by catter1** [comment]
This would be something to bring up with Tectonic, since they change how Terralith works.
