### ISSUE TITLE
[Bug] Lectern in desert outpost can't be used

### ISSUE THREAD

**Issue by lonevox** [Stardust-Labs-MC/Terralith#134]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.5.1

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Whenever the lectern is interacted with, the GUI opens for a split second before it forcefully closes. There are no errors in the console.

https://github.com/Stardust-Labs-MC/Terralith/assets/38600896/45b66db1-2c56-40a2-bc5a-3c37bd2caab7

**Comment by catter1** [comment]
Fixed in future 2.5.4 for 1.21 - 1.20.x fix will come out later
