### ISSUE TITLE
[Bug] Loot table in desert village not working.

### ISSUE THREAD

**Issue by begreatnic** [Stardust-Labs-MC/Terralith#140]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.5.1

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Loot table for the specific container "terralith:village/desert/fisherman" resolved to empty and could not generate any loot.

### Additional context

Note that this is on Minecraft version 1.20.1 using Fabric.

**Comment by catter1** [comment]
Fixed for future 2.5.4 version
