### ISSUE TITLE
[Bug] Xaero Minimap shows decorated name for Terralith's biomes

### ISSUE THREAD

**Issue by frosthuuuund** [Stardust-Labs-MC/Terralith#143]
### What Minecraft version(s) does this apply to?

1.21

### Project version

v2.5.3

### Mod or datapack version?

Datapack

### Describe the bug

I don't think this is mod issue.
biome.terralith.forested_highlands

**Comment by catter1** [comment]
Yse our resourcepack [Sparkles](https://modrinth.com/resourcepack/sparkles), it fixes that issue.
