### ISSUE TITLE
[Enhancement] how can i download the texture

### ISSUE THREAD

**Issue by Onionbhai** [Stardust-Labs-MC/Terralith#144]
### Describe your enhancement/improvement, with context and reasoning.

I jave used the data pack and this datapack is amazing and I just like the redish colour leaves and the grass colour so I just want to know how can I download the texture pack of this mod ( I the pack available or not and if available then pls give the link and if not available then make the texture pack also ) and one again I m saying that this is the best world generation mod I have ever seen

**Comment by catter1** [comment]
There is no texturepack for Terralith. Instead, it's a Vanilla feature that makes the leaves different colors. It's biome dependent - if you place an oak leaf in a Sakura bioem, it will be pink. If in Forested Highlands, it will be red. For example.
