### ISSUE TITLE
Structure only version

### ISSUE THREAD

**Issue by Haskellered** [Stardust-Labs-MC/Terralith#145]
### Describe your enhancement/improvement, with context and reasoning.

A structures only version of the mod would allow me to use the structures with other terrain generation mods, for example Terra.

**Comment by catter1** [comment]
This is not planned, as we already have structure-only mods. Check out Structory and Structory: Towers.

**Comment by Haskellered** [comment]
Thanks

**Comment by Haskellered** [comment]
Is there a chance Structory will be uploaded to Modrinth at some point?

**Comment by catter1** [comment]
I do not have an answer of that unfortunately; it is not my decision.
