### ISSUE TITLE
[Bug] mage_tower Missing spire

### ISSUE THREAD

**Issue by Jan-Arbus** [Stardust-Labs-MC/Terralith#149]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.5.4

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Its variants also lack the spire.
![2024-07-26_23 51 03](https://github.com/user-attachments/assets/2f72dfbc-25a9-4dd5-9c8b-7cbb7883b0d7)

### Additional context

The Minecraft version is actually 1.21, but there is no 1.21 option available in the issue form

**Comment by catter1** [comment]
Fixed for 2.5.5

**Comment by Lumiko32** [comment]
Fabric 1.20.1 haven't updated yet, the latest version is still 2.5.4,please update to fix this

**Comment by catter1** [comment]
I haven't had time for the 1.20.x backport yet, will happen eventually
