### ISSUE TITLE
[Bug] Generation replaces blocks on structures 1.21

### ISSUE THREAD

**Issue by MRSPLASHLOL** [Stardust-Labs-MC/Terralith#152]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.5.1

### Mod or datapack version?

Datapack

### Describe the bug

Many structures have some of their blocks replaced with biome generation. One of the most common structures I find this happening with is the desert village. It happens a lot in the desert oasis biome, where moss replaces some of the sandstone used in the structure.

**Comment by catter1** [comment]
Had some discussion with others. Unfortunately, it's not *practical* to fix this issue. Possible, but we would have to change the generation order of a lot of things, which could have unintended consequences. We will hopefully see if Mojang provides a better alternative in the future.
