### ISSUE TITLE
[Bug] Explorer maps have wrong biome layout

### ISSUE THREAD

**Issue by frosthuuuund** [Stardust-Labs-MC/Terralith#153]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.5.4+1.21

### Mod or datapack version?

Datapack

### Describe the bug

I don't think this treasure map reflects the real world
![treasuremap](https://github.com/user-attachments/assets/4eecfc12-fda8-4337-b3b7-fce653825ec9)

**Comment by catter1** [comment]
We cannot control how explorer maps work, so wouldn't be an issue on our end if it was the case. Likely would be some seed shifting issue... but I don't think this is what happens here.

If you look at the preview of unexplroed chunks, yes, it looks off. But for the actual generated map, from the extremely limited amount I can see, the explored parts looks to match the terrain perfectly. Not an issue.
