### ISSUE TITLE
Issue with worldgen caused by mangrove swamp bug

### ISSUE THREAD

**Issue by Waffler-jpg** [Stardust-Labs-MC/Terralith#154]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.5.4

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Issue with loading mangrove swamp causes game to crash at around 2% loaded of a world https://mclo.gs/jRARzAu

### Additional context

SOLVED

**Comment by catter1** [comment]
@Waffler-jpg install the [Cyanide](https://modrinth.com/mod/cyanide) mod, let it crash again, and send that log. It will give me more information on what may be causing the issue

**Comment by Waffler-jpg** [comment]
> @Waffler-jpg install the [Cyanide](https://modrinth.com/mod/cyanide) mod, let it crash again, and send that log. It will give me more information on what may be causing the issue

I'm using terralith on 1.20.4, there isn't a version of cyanide available

**Comment by catter1** [comment]
The latest version works on 1.20.4 - I thought there was marked as such, but I guess not.

**Comment by Waffler-jpg** [comment]
> The latest version works on 1.20.4 - I thought there was marked as such, but I guess not.

Thanks, I'll update in a bit as it's late where I am

**Comment by Waffler-jpg** [comment]
> The latest version works on 1.20.4 - I thought there was marked as such, but I guess not.

Turns out it was an issue caused by geophilic, a different mod, not an issue with terralith itself, they were conflicting
