### ISSUE TITLE
[Bug] The Volcanic Peak biome becomes corrupted

### ISSUE THREAD

**Issue by DracoHero** [Stardust-Labs-MC/Terralith#156]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.5.4

### Mod or datapack version?

Mod (Forge)

### Describe the bug

This generation error happens when I activate the options to allow the maximum height in the tectonic.json config, now I don't know if perhaps the conflict is due to another generation mod, I will go through the list of mods that I have just in case.
[Mods List.json](https://github.com/user-attachments/files/16570625/Mods.List.json)

With the option activated in true:

![2024-08-10_14 42 07](https://github.com/user-attachments/assets/a1efe75c-ff6e-4f7c-b776-a3380f9232a7)
![2024-08-10_14 42 14](https://github.com/user-attachments/assets/41397b5b-0b58-42b1-9160-951565095a48)

With the option activated in false:

![2024-08-10_14 47 07](https://github.com/user-attachments/assets/84682457-5a8b-4751-902b-de885588e91c)
![2024-08-10_14 47 12](https://github.com/user-attachments/assets/41221812-39dd-424f-98fe-56a1b7967780)

**Comment by catter1** [comment]
This is an issue with Tectonic, and should be reported there instead.
