### ISSUE TITLE
[Bug] Translation Bugs with Biomes

### ISSUE THREAD

**Issue by makumaku1974** [Stardust-Labs-MC/Terralith#157]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

2.5.4

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

Translation bugs with biomes.
![image](https://github.com/user-attachments/assets/99ad1fad-e81d-425d-97d8-761275de3e2e)

**Comment by catter1** [comment]
This is solved by using our resource pack [Sparkles](https://modrinth.com/resourcepack/sparkles)

**Comment by makumaku1974** [comment]
thanks
