### ISSUE TITLE
Compatibility with Biome Info mod?

### ISSUE THREAD

**Issue by Scarlet-Fury** [Stardust-Labs-MC/Terralith#158]
Minecraft Version: 1.20.1

Forge Version: 47.3.0

Mods installed: Terralith & Biome Info

So, I like using Terralith with the Biome Info mod, as it lets you see what biome you're in without having to press F3 all the time, but for some reason it displays funny in the Biome Info mod as

 biome.terralith.snowy_badlands 

(As an example) 

I asked the author of Biome Info about it, and he said it's cause Terralith has no built in translations for the mod, so Biome Info can't display it properly, so it's an issue on your end

Any plans to fix this?

![Screenshot_20240814_025012_GitHub.jpg](https://github.com/user-attachments/assets/80a542de-7e4b-4c4d-8605-9b5e87e65878)

![357605323-7cdc3787-cd09-402c-af82-a3ba6b75ae72.png](https://github.com/user-attachments/assets/a567890e-59e9-4eed-b5b5-4da3e36f9188)

**Comment by catter1** [comment]
The translations are included in the Terralith mod by default. However, the last couple of versions (I think 2.5.1+?), my mod builder process has been broken, so the translations have not been automatically added. And frankly I forgot about it. So once I am able to fix my builder, they will be included in the jar.

As a temporary solution, you can download and use our resourcepack [Sparkles](https://modrinth.com/resourcepack/sparkles), which has the translations for our biomes.
