### ISSUE TITLE
[Bug] No horse or sheep generated, instead too many donkeys and horses

### ISSUE THREAD

**Issue by AnterCreeper** [Stardust-Labs-MC/Terralith#159]
### What Minecraft version(s) does this apply to?

1.19 - 1.19.3

### Project version

v2.3.12

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

No biome generate horse or sheep,
instead too many donkeys and horses(around 10+ biomes)
The creature balance breaks the vanilla experience.

**Comment by catter1** [comment]
All passive mobs generate in Terralith biomes. Not every biome has every single passive mob in it, but they do exist. For example, one biome might spawn pigs, chickens, and horses; while another spawns cows, chickens, and donkeys.

However, it is Terralith's fault for there to generate a **lot** of animals at once, which can make it seem like there's an imbalance. See one of our old FAQs below:
![image](https://github.com/user-attachments/assets/b92b36e9-f1eb-4cb7-ad74-6bad949d7c98)

As shown at the bottom of the FAQ, this was changed in 2.5.0, which is for 1.20+. I don't have any ETA whatsoever, but I may make a "final" 1.19.x update which backports a lot of things from 2.5.0. But for now, I will mark this issue as not planned.

**Comment by AnterCreeper** [comment]
Thanks for your explaining!
