### ISSUE TITLE
[Bug] java.lang.StackOverflowError: Exception in server tick loop

### ISSUE THREAD

**Issue by WingFrosty** [Stardust-Labs-MC/Terralith#160]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

v2.5.4

### Mod or datapack version?

Datapack

### Describe the bug

When updating the datapack from version v2.5.3 to v2.5.4 on an existing world, it crashes with the following error:

java.lang.StackOverflowError: Exception in server tick loop
	at net.minecraft.class_6916$class_6937.equals(class_6916.java:783)
	at java.base/java.util.Objects.equals(Unknown Source)
	...

### Additional context

Steps to reproduce:

1. Download the world from [here](https://drive.google.com/file/d/1X18nnEiqffFgfQ5ZPr1yTF6CwKZbTnct/view?usp=sharing)
2. Add the world to the _saves_ folder
3. Start Minecraft and enter the world

Crash file:
[crash-2024-08-21_02.12.11-server.txt](https://github.com/user-attachments/files/16684081/crash-2024-08-21_02.12.11-server.txt)

If the Terralith datapack is replaced with version v2.5.3 (redownload world files and replace datapack), the world starts just fine.

**Comment by catter1** [comment]
This is an issue with Terratonic load order that can occur when updating a pack. If you update Terralith, it will make it load above Terratonic, which is incorrect. Remove both datapacks, and then readd them to make sure Terratonic is loaded on top.
