### ISSUE TITLE
[Enhancement] Lack of publicly available documentation on how to modify world gen parameters for terralith

### ISSUE THREAD

**Issue by uczpre** [Stardust-Labs-MC/Terralith#161]
### Describe your enhancement/improvement, with context and reasoning.

Would love to know how ! without discord , i cant use discord.
specificly on how to increase biome size.

**Comment by catter1** [comment]
This is planned in the future, but it will be a huge undertaking to do it correctly. With other important things (such as the Incendium rewrite and maintaining everything), this has low priority unfortunately.

In the meantime, here's the guide taken from our Discord if you'd like it. 
![image](https://github.com/user-attachments/assets/bbb89c8e-11e9-46b9-99e9-ca3894c60cfa)

**Comment by uczpre** [comment]
Why not make that more publicly available ? like say in the wiki page , sure 7 year olds are gonna piss their pants seeing all those HaCKer LiNEs , but its good enough and is better than nothing !

**Comment by uczpre** [comment]
i also cant see why someone cant make a tool that would basicaly just those .json values inside the .jar/datapack folder

**Comment by uczpre** [comment]
if this info is public , i bet someone will make a tool/easier way to change it someday ! ;D

**Comment by catter1** [comment]
> Why not make that more publicly available ?

As I said, yes, this is something I plan to do. I just do not have the time for it, nor is it high priority.

> if this info is public , i bet someone will make a tool/easier way to change it someday ! ;D

This is already planned.
