### ISSUE TITLE
[Bug] Instant Crash when making a World

### ISSUE THREAD

**Issue by Dreuzz** [Stardust-Labs-MC/Terralith#166]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

2.5.4

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

As the title already says my game instantly crashed when trying to make a new world in 1.21 

see log here:
https://mclo.gs/hvlh1PX

**Comment by Dreuzz** [comment]
I tried out the Datapack and it seems like it works fine? I have to check if it overwrites tectonic tho

**Comment by catter1** [comment]
Very odd, I might just recommend trying to redownloading the Terralith mod? Not sure what else would cause it.

**Comment by Dreuzz** [comment]
I have to note that the same crash applies to [Amplified Nether](https://modrinth.com/mod/amplified-nether) and [Nullscape](https://modrinth.com/mod/nullscape) too. The modpack I'm using is quite big and may cause trouble because of its size

**Comment by catter1** [comment]
If you are still having problems, reopen this issue while providing a new crashlog, with the latest version of Terralith and Tectonic installed.
