### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Divanzkar** [Stardust-Labs-MC/Terralith#167]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

v2.5.4

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

![Screenshot 2024-09-11 012243](https://github.com/user-attachments/assets/6dfbb935-fcaa-4a28-b666-2474bd597774)
The tree generation is sinking, i try it in aternos multyplayer and generate the same thing with the same problem, happen in most biome.

### Additional context

Tree Generation Sinking

**Comment by catter1** [comment]
This is on purpose. They are not supposed to be trees, they are bushes.
