### ISSUE TITLE
[Bug] Mods using biome names actually use biome id's

### ISSUE THREAD

**Issue by Hippopipo** [Stardust-Labs-MC/Terralith#168]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

v2.5.4

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

Biome names in map mods and nature's compass show up as their id's, not their names.
![screenshot](https://github.com/user-attachments/assets/a1c82397-ac96-443a-b6cc-3d7e9d0c2d8c)

**Comment by catter1** [comment]
Known issue. Normally this is not the case with the mod version of Terralith, but because my build pipeline is currently broken, the translations are not being packaged with the mod. See here for more information: https://github.com/Stardust-Labs-MC/Terralith/issues/158#issuecomment-2289347487
