### ISSUE TITLE
Can't disable terrainlith when using custom datapacks

### ISSUE THREAD

**Issue by Lightning323** [Stardust-Labs-MC/Terralith#169]
When creating a world that uses a custom datapack like this one: [aerolith (datapack)](https://modrinth.com/datapack/aerolith/version/1.3.0)

The data-pack doesn't work even if it is top priority when added. Not only that but I can't **disable** terralith when i just want to play in a single biome world. **is there a way to turn terralith OFF with some worlds?** my only other option right now is to play without terralith completely.

**Comment by catter1** [comment]
There is not. Same reasoning as #113 - see it for more information.
