### ISSUE TITLE
[Bug] Most trees are only one block high

### ISSUE THREAD

**Issue by Ze-Crusader** [Stardust-Labs-MC/Terralith#170]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

v2.5.5

### Mod or datapack version?

Datapack

### Describe the bug

Like said in the title, most trees have only one oak block, like huge bush on the ground.

![2024-09-28_19 02 26](https://github.com/user-attachments/assets/fb547eb1-90e5-40f2-912c-e897354c5ec6)
![2024-09-28_19 03 04](https://github.com/user-attachments/assets/2223152c-4a26-4b2f-b265-b2d643e2202d)
![2024-09-28_19 03 23](https://github.com/user-attachments/assets/530b39dc-d38c-45a5-b6c4-04c17adfb579)

### Additional context

Only Terralith was used, no other datapack.

**Comment by catter1** [comment]
These are intentional. They are meant to do exactly like you said - look like large bushes.
