### ISSUE TITLE
[Enhancement] Add (back) the ability to grow a custom dark oak in forest highlands etc

### ISSUE THREAD

**Issue by emiellr** [Stardust-Labs-MC/Terralith#172]
### Describe your enhancement/improvement, with context and reasoning.

Back in 2022 there was a change that allowed people to grow the custom trees that Terralith offers by bonemealing the ground near a dark oak tree, but a couple months later is was 'temporarily removed'. Would you consider adding it back? Making the trees by hand is quite a chore. Since dark oaks don't grow with a single sapling anyway, maybe have the custom trees grow when you use a single sapling?

**Comment by catter1** [comment]
No, we _currently_ do not have any plans to add this back into base Terralith. However, one of our community members has created an addon called [Custom Biome Saplings](https://modrinth.com/datapack/terralith-biome-saplings), which does add a similar functionality if you're interested.
