### ISSUE TITLE
[Enhancement]How can I check those unloaded chunks like Chunkbase  in minecraft without the mod?

### ISSUE THREAD

**Issue by CMkuroinu** [Stardust-Labs-MC/Terralith#178]
### Describe your enhancement/improvement, with context and reasoning.

I am so sorry about my excuse for you and my poor English.I have a problem that I want to find a suitable area to begin my game.However, because the mod has changed the way to load the chunk.seems that chunkbase is not useful in my world. Then, how can I check those data of areas which are not loaded like chunkbases?
I felt sorry about my poor English and my excuse ,have a nice day.

**Comment by catter1** [comment]
We recommend using [datapack map](https://map.jacobsjo.eu/)

And no need to apologise for your English, it is good
