### ISSUE TITLE
[Bug] Certain biomes (like volcanic.crater) generating incorrectly

### ISSUE THREAD

**Issue by owolordATTACKS** [Stardust-Labs-MC/Terralith#180]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

2.5.6

### Mod or datapack version?

Datapack

### Describe the bug

When generating chunks, some biomes generate covered in a layer of grass, like so:
![2024-11-15_16 14 28](https://github.com/user-attachments/assets/20fc2bb9-8dc9-4c71-927e-7572aad2a192)
Running a paper server on Minecraft 1.21. Terralith is the only datapack installed.
List of plugins:
![Снимок экрана (209)](https://github.com/user-attachments/assets/b38e095a-0072-4aa1-a3e3-c73fc7078dfb)

**Comment by catter1** [comment]
Can you share the seed and coordinates used in the image?

**Comment by owolordATTACKS** [comment]
This happens on every world I generate.
-7986274189292398635
3921 120 -2957 - Not the same seed, the original has been lost since then, same phenomena happens here.

**Comment by catter1** [comment]
I pulled up a version of Terralith 2.5.6 on 1.21.1, with the same seed and coords that you sent. What I see is intended - if you are not seeing the same thing, then something might be interfering. I might recommend resetting the world just to test if it didn't install properly the first time.

![2024-11-17_12 31 29](https://github.com/user-attachments/assets/3bae42d2-efaf-4651-b14b-d5ae01aa1d80)

**Comment by catter1** [comment]
If this is still an issue, feel free to reopen it with more detail. Closing for now.
