### ISSUE TITLE
Server Crash Using Datapack

### ISSUE THREAD

**Issue by Rgiulini99** [Stardust-Labs-MC/Terralith#22]
# The Terralith Datapack Crashes In Startup
** Idk Why Crash **[latest.log](https://github.com/Stardust-Labs-MC/Terralith/files/11172851/latest.log)

**Comment by catter1** [comment]
This does not appear to be an issue with Terralith. You're using the *1.17.1* compatibility datapack for DNL/Terralith - I'd recommend getting an updated version

**Comment by Rgiulini99** [comment]
> This does not appear to be an issue with Terralith. You're using the _1.17.1_ compatibility datapack for DNL/Terralith - I'd recommend getting an updated version

Im Using 1.19.3 Version of Terralith
