### ISSUE TITLE
[Bug] Superflat is ignored.

### ISSUE THREAD

**Issue by mageowl** [Stardust-Labs-MC/Terralith#29]
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

6.2.1

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

When generating a superflat world, Terralith instead generates a normal world.

**Comment by catter1** [comment]
This is unfortunately nothing that we can control, this is vanilla behavior. The only way to avoid it is to disable Terralith when generation/loading a Superflat world, or using the datapack version so you can specify it per world.

This will not longer be an issue once [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949) is fixed

**Comment by mageowl** [comment]
Thank you.
