### ISSUE TITLE
Structure config

### ISSUE THREAD

**Issue by Fleki2** [Stardust-Labs-MC/Terralith#33]
### Describe your enhancement/improvement, with context and reasoning.

can you please add option to enable/disable terralith structures like fortified villages? Or maybe add option to make them very rare or spawn far away from the spawn?

Thanks. :)

**Comment by catter1** [comment]
Datapacks cannot have configs. However, feel free to use this: https://github.com/ApolloDatapacks/pack-library/raw/main/stardust-pack-changes/no-terralith-structures.zip
