### ISSUE TITLE
[Bug] Extremely long loading times for Terralith biomes when used with the Waystones mod

### ISSUE THREAD

**Issue by thanostrich** [Stardust-Labs-MC/Terralith#36]
### What Minecraft version(s) does this apply to?

1.18.2

### Project version

2.2.1a

### Mod or datapack version?

Mod (Forge)

### Describe the bug

When using the Waystones mod to teleport, it takes 5-10 times longer to teleport if the destination is in a Terralith biome as opposed to a vanilla biome.

**Comment by catter1** [comment]
There's nothing that Terralith can do about that. Terraltih is a datapack, and add biomes the exact same way Vanilla does. the game treats Terralith biomes the exact same, and by proxy, so should Waystones (in theory at least).
