### ISSUE TITLE
Terralith world generator overrides selection in world creation screen

### ISSUE THREAD

**Issue by mrbuilder1961** [Stardust-Labs-MC/Terralith#4]
I was trying to make a void world for testing, and no matter what I said the world generator to, it always created a Terralith world.

https://mclo.gs/IcNhrD1

Minecraft 1.19.2, Terralith jar v2.3.6

**Comment by catter1** [comment]
Apologies, as I do not check here for support issues.

Anyways, Terralith is a datapack, so it has no world type, nor does it care about them. If you want to make a void world, you need to disable the mod.
