### ISSUE TITLE
[Bug] Feature Order Cycle with Ecospherical Expansion

### ISSUE THREAD

**Issue by catter1** [Stardust-Labs-MC/Terralith#45]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.5

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Taken from #42, issue reported by @SupGamerNL

[Crash Logs](https://mclo.gs/l7O5xtZ)

**Comment by catter1** [comment]
@SupGamerNL, can you install the [Cyanide mod](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) and create a world with the same mods again? Send the resulting crash log via [mclogs](https://mclo.gs/), and this will help me figure out if its EE's or Terralith's fault.

**Comment by SupGamerNL** [comment]
I tried again as you suggested with the Cyanide mod.
Here are the results:
[crash-2023-09-06_11.30.15-server.txt](https://github.com/Stardust-Labs-MC/Terralith/files/12535778/crash-2023-09-06_11.30.15-server.txt)
[latest.log](https://github.com/Stardust-Labs-MC/Terralith/files/12535781/latest.log)

Both Terralith and Ecospherical Expansion are using their latest versions.
TL: v2.4.5
[EE](https://modrinth.com/datapack/ecospherical-expansion-lite/versions?g=1.20.1) (Lite, datapack version): v2.1.1

Edit: here are the logs via mclogs:
[crash-2023-09-06_11.30.15-server.txt](https://mclo.gs/k0sypBN)
[latest.log](https://mclo.gs/URh6LVD)

**Comment by catter1** [comment]
Thank you for your report - did some investigating, and I believe I found the issue on Terralith's end. I will do some testing, and if my fix is correct, I will release 2.4.6 with the patch. I'm not sure entirely when it will release since I am waiting on something else, but will be as soon as possible.

**Comment by SupGamerNL** [comment]
Well thanks, then I and possibly many others are happy to wait!
