### ISSUE TITLE
[Enhancement] Andesite and diorite generation

### ISSUE THREAD

**Issue by nopeless** [Stardust-Labs-MC/Terralith#47]
### Describe your enhancement/improvement, with context and reasoning.

This might be a stupid issue, I apologize in advance

I am playing Create mod with Terralith generation, and it is impossible to find andesite (nor diorite, which can be used with cobblestone to create andesite).

https://www.reddit.com/r/CreateMod/comments/u3i6j6/unable_to_find_andesite_with_terralith_and_its/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Reddit post explaining the same issue.

I think there should be some andesite

**Comment by catter1** [comment]
The stones exist. Explanation taken from our FAQ, and [wiki link](https://stardustlabs.miraheze.org/wiki/Terralith#Andesite_boulders):
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/9f071ea7-85f6-4dfd-8c17-7488574efc83)
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/cdc5c3f7-c14c-4268-8d89-722ac07b8129)
