### ISSUE TITLE
[Crash on world load] 1.20.1 latest forge version: exception generating new chunk

### ISSUE THREAD

**Issue by Daltaxy** [Stardust-Labs-MC/Terralith#49]
### What Minecraft version(s) does this apply to?

1.20

### Project version

Terralith_1.20.2_v2.4.7.jar

### Mod or datapack version?

Mod (Forge)

### Describe the bug

crashes when I try to load my previous world, and the log mentions Terralith in multiple spots, the cherry biome specifically
[latest.log](https://github.com/Stardust-Labs-MC/Terralith/files/12824946/latest.log)

**Comment by Daltaxy** [comment]
also fixed by going back to the previous version of terralith

**Comment by catter1** [comment]
Please install the [Cyanide mod](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) and boot up the game with the same mods again. Send that log. Cyanide will tell me exactly which parts of the biomes are causing the issue so I can investigate it.

When you send the log, use [mclogs](https://mclo.gs) to send them, since its easier to view.

**Comment by Daltaxy** [comment]
thank you for providing links, will do it right away

**Comment by Daltaxy** [comment]
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/111076631/070f3c72-7f7f-41e6-a9fb-3116048514fd)
well...
and trying to create a new world right after: 
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/111076631/0f9844bb-a862-4d01-a518-c5b281ed5739)

https://mclo.gs/tjutSYZ

**Comment by catter1** [comment]
Send that log to Apotheosis - there's an error with their mod. It looks like an extra mod that Cyanide caught - so temporary remove Apotheosis and try again to see if we can get the Terralith/BoP error.

(I will check your response tomorrow)

**Comment by Daltaxy** [comment]
there we go, I got it (created a new world because I don't really want to try loading my own world without apotheosis)
latest.log https://mclo.gs/dDg0yvK
crash report: https://mclo.gs/cR6CcpF
link to the apotheosis thread: https://github.com/Shadows-of-Fire/Apotheosis/issues/1035

**Comment by catter1** [comment]
Looks like now it's complaining about Pineapple Delight ([exact line](<https://mclo.gs/dDg0yvK#L7656>))

**Comment by Daltaxy** [comment]
> Looks like now it's complaining about Pineapple Delight ([exact line](https://mclo.gs/dDg0yvK#L7656))

fixed by removing that mod, thanks and sorry for the delay
