### ISSUE TITLE
[Bug] Broken dripleaf generation in Orchid Swamp

### ISSUE THREAD

**Issue by Apollounknowndev** [Stardust-Labs-MC/Terralith#50]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.7

### Mod or datapack version?

Datapack

### Describe the bug

![image](https://github.com/Stardust-Labs-MC/Terralith/assets/102649729/b1a597de-dd9b-41ba-9f69-b9d0fb105fb7)

**Comment by catter1** [comment]
Fixed in future Terralith version (by OP).
