### ISSUE TITLE
[Bug] Biome: terralith:alpine_highlands missing biome tags?

### ISSUE THREAD

**Issue by RaidenKoizuma** [Stardust-Labs-MC/Terralith#53]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.7

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Seems Biome: terralith:alpine_highlands might be missing biome tags. Made a report https://github.com/TeamMetallurgy/Aquaculture/issues/418 here about a different issue since and they suggested there might be missing tags in the biome.

**Comment by catter1** [comment]
That is incorrect. I commented on the linked issue explaining it. I'll keep this issue open for a little bit, just in case.
