### ISSUE TITLE
[Bug] Strange generation in painted mountains

### ISSUE THREAD

**Issue by user24235412** [Stardust-Labs-MC/Terralith#61]
### What Minecraft version(s) does this apply to?

1.20

### Project version

 v2.4.7 

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Seems that painted mountains surface only generates white terracotta. Also this is not a problem in versions before 2.4.7.
![2023-10-27_16 55 54](https://github.com/Stardust-Labs-MC/Terralith/assets/149202975/59524652-263c-4b6c-97eb-46e55dc45a86)

**Comment by catter1** [comment]
Fixed for v2.4.8
