### ISSUE TITLE
Pilllager Outposts cant spawn anywhere in my world now that terralith is installed 

### ISSUE THREAD

**Issue by rxpapi** [Stardust-Labs-MC/Terralith#63]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.8

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

when i use chunkbase or the locate command it tells me theres one somewhere but when i go there its not there and ive also discovered up to 50,000 ungenerated chunks

### Additional context

i had pillager outposts in old vanilla chunks but not a single one in terralith chunks

**Comment by Apollounknowndev** [comment]
Terralith doesn't touch pillager outposts other than adding the structure to its custom biomes. Not caused by Terralith.
