### ISSUE TITLE
Terralith doesn't upgrade the structures[Bug]

### ISSUE THREAD

**Issue by SadPlayz712** [Stardust-Labs-MC/Terralith#64]
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

2.3.12

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

![Screenshot 2023-11-13 064710](https://github.com/Stardust-Labs-MC/Terralith/assets/150652196/a753a015-fd93-4337-916d-5944c11399f3)
It shows a normal village(even though I had the programmer art off)(*)

**Comment by catter1** [comment]
Terralith does not replace normal villages. Terralith adds its own villages, so you will find both.

**Comment by SadPlayz712** [comment]
ok
