### ISSUE TITLE
[Bug] Newest version makes servers crash on startup, saying datapack errors

### ISSUE THREAD

**Issue by NovaViper** [Stardust-Labs-MC/Terralith#80]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.10

### Mod or datapack version?

Mod (Forge)

### Describe the bug

When I updated Terralinth to v2.4.10, the server immediately dies as the mod tries to load up its datapack, with [this error in the logs](https://github.com/Stardust-Labs-MC/Terralith/files/13607592/error.txt). In particular, it's talking about this new file, [data/terralith/worldgen/structure_set/regular.json](https://github.com/Stardust-Labs-MC/Terralith/blob/5438c0138cb8e016b97a32d0bce51b12b0988f39/data/terralith/worldgen/structure_set/regular.json). Going back to v2.4.8 made it work again

**Comment by catter1** [comment]
I just published a hotfix for it, download 2.4.11
