### ISSUE TITLE
[Enhancement] Add Terralith's biomes to "Aventuring Time" advancement

### ISSUE THREAD

**Issue by Lemonzyy** [Stardust-Labs-MC/Terralith#87]
### Describe your enhancement/improvement, with context and reasoning.

I think having all the biomes available in the "Aventuring Time" advancement might make it more fun to find all the existing biomes, including those in Terralith.

**Comment by catter1** [comment]
We have debated this before, but a long time ago we came to the decision to not modify the advancement. However, the door is still open for us to make some sort of addon that could do this. It's also very easily possible for *anyone* to make an addon for this change and apply it.

But I digress - although it does seem like a simple and obvious enhancement, we did decide against it for now.
