### ISSUE TITLE
Game crashes on discovering new chunks

### ISSUE THREAD

**Issue by Firro007** [Stardust-Labs-MC/Terralith#88]
### What Minecraft version(s) does this apply to?

1.20

### Project version

Terralith_1.20.4_v2.4.11.jar

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Hi,
when i try to discover a new chunk in any direction, game immediately crashes. I tried to regenerate chunks in MCA selector but the issue is still there.

### Additional context

Log file link:
The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / terralith:blooming_valley]=net.minecraft.world.level.biome.Biome@2fbfde72}, Reference{ResourceKey[minecraft:worldgen/biome / terralith:lavender_forest]=net.minecraft.world.level.biome.Biome@71c3fe82}]

**Comment by catter1** [comment]
This is an issue with Croptopia. The issue has been made [here](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/577). Will have to wait for them to fix it.

**Comment by Firro007** [comment]
Okay, thanks for your reply.
