### ISSUE TITLE
I dont know whats up[Bug]

### ISSUE THREAD

**Issue by LightWardenX** [Stardust-Labs-MC/Terralith#94]
### What Minecraft version(s) does this apply to?

1.18.2

### Project version

v2.2.3

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

For some reason I can't load into a world with this mod installed, even when i create a new one it just won't load me in, its just stuck at 100%

### Additional context

my computer model is i5-1235U. And all I have are a few other vanilla plus mods installed with a resource pack and shaders.

**Comment by catter1** [comment]
1. 2.2.3 is quite outdated. Try updating to 2.2.5 (there's a small issue with 2.2.6, so wouldn't recommend). Make sure to download the new dependencies.
2. Does the issue persist with **JUST** Terralith? If not, it's likely another mod causing the issue
3. If the issue does persist with the updated version and Terralith by itself, send your logs

**Comment by LightWardenX** [comment]
will do

**Comment by catter1** [comment]
Feel free to reopen if still needed, but given that the issue is a week old with no response, I will assume it has been resovled.
