### ISSUE TITLE
Lush caves generate on the surface

### ISSUE THREAD

**Issue by squareroot-of-false** [Stardust-Labs-MC/Terralith#96]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.11

### Mod or datapack version?

Datapack

### Describe the bug

A lush caves biome generated on the surface between some of the spires in a windswept spires biome. It was clearly not part of the entrance to a cave.

### Additional context

Seed: 3548282436416288536
Coordinates: -1359 219
<img width="2560" alt="Terralith-lush-caves-bug" src="https://github.com/Stardust-Labs-MC/Terralith/assets/123512035/496a50bb-71a6-4e69-9152-bda0b3dc227b">
<img width="2560" alt="Screenshot 2024-01-25 at 4 59 48 PM" src="https://github.com/Stardust-Labs-MC/Terralith/assets/123512035/89a0c4e1-9331-4dce-b032-8c336a770f2b">

**Comment by squareroot-of-false** [comment]
I was also using Incendium and Nullscape, but those shouldn’t affect Overworld generation.

**Comment by catter1** [comment]
Good catch, and thanks for the F3 screen! That is exactly what I needed to help solve the issue. A fix has been made, and will release with the next version of Terralith.
