### ISSUE TITLE
[Bug]Crash. Your mod was directly mentioned

### ISSUE THREAD

**Issue by ArrowFX** [Stardust-Labs-MC/Terralith#97]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.11

### Mod or datapack version?

Mod (Forge)

### Describe the bug

I used waystones to tp to a distant village, and I crashed after about 1-2 minutes.

https://paste.ee/p/NeOLi

**Comment by catter1** [comment]
Install [this](https://modrinth.com/mod/cyclic-crash-fixer) mod, and the crash will be fixed.

**Comment by ArrowFX** [comment]
Worked like a charm! Have been playing for 3 hours now and no crash! Thanks for recommending that mod!
